// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "41d9630b058398094295b89676a7d049ed89b3394ab99f251de31ae119aed73a")
